name: Frontend Deploy to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'packages/frontend/**' 

defaults:
  run:
    working-directory: packages/frontend 
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Decode .env file depending on branch
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "${{ secrets.APPLICATION_ENV_PROD }}" | base64 --decode > .env
          else
            echo "No environment file for this branch"
          fi

      - name: Create output
        run: sh ./build.sh

      - name: Push to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: "output"
          destination-github-username: "OZIIJIN"
          destination-repository-name: "sohawgi_Front"
          user-email: ${{ secrets.EMAIL }}
          commit-message: |
            ${{ github.event.commits[0].message }} / ${{ github.run_id }}
          target-branch: main
          create-target-branch-if-needed: true
