ALTER TABLE schedule ADD COLUMN type VARCHAR(255);

UPDATE schedule SET type = 'SCHEDULE';

ALTER TABLE schedule MODIFY COLUMN type VARCHAR(255) NOT NULL;

ALTER TABLE schedule MODIFY COLUMN hour INT NULL, MODIFY COLUMN minute INT NULL;
